In [2]:
import numpy as np

In [3]:
a1 = np.array([[4,6,4],[2,1,2],[5,6,7]])

In [4]:
a1.ravel()

array([4, 6, 4, 2, 1, 2, 5, 6, 7])

In [5]:
a1[:,1]

array([6, 1, 6])

In [6]:
a1[1:][:,1]

array([1, 6])

In [7]:
b1 = np.resize(a1, (6,6))
b1

array([[4, 6, 4, 2, 1, 2],
       [5, 6, 7, 4, 6, 4],
       [2, 1, 2, 5, 6, 7],
       [4, 6, 4, 2, 1, 2],
       [5, 6, 7, 4, 6, 4],
       [2, 1, 2, 5, 6, 7]])

In [8]:
b1[0:5:2][:,3:]

array([[2, 1, 2],
       [5, 6, 7],
       [4, 6, 4]])