In [1]:
import numpy as np

In [3]:
A = np.array([[1, 2, 3],[2,-2,1],[3,1,2]])
b1 = np.array([1,2,3])
b2 = np.array([-1,-2,-3])

In [4]:
A@b1

array([14,  1, 11])

In [5]:
A.T

array([[ 1,  2,  3],
       [ 2, -2,  1],
       [ 3,  1,  2]])

In [6]:
np.dot(b1, b2)

-14

In [7]:
np.cross(b1, b2)

array([0, 0, 0])