In [2]:
import numpy as np

In [3]:
A = np.array([[3, 2, 1],[5,-5,4],[6,0,1]])
c = np.array([4,3,0])

In [4]:
np.linalg.solve(A,c)

array([-0.49056604,  1.26415094,  2.94339623])

In [5]:
A = np.array([[4,2,2],[2,4,2],[2,2,4]])

In [6]:
np.linalg.eig(A)

(array([2., 8., 2.]),
 array([[-0.81649658,  0.57735027, -0.32444284],
        [ 0.40824829,  0.57735027, -0.48666426],
        [ 0.40824829,  0.57735027,  0.81110711]]))

In [7]:
w, v = np.linalg.eig(A)

In [8]:
A@v[:,1]

array([4.61880215, 4.61880215, 4.61880215])

In [9]:
w[1]*v[:,1]

array([4.61880215, 4.61880215, 4.61880215])